<?php

/**
 * @license GNU General Public License < https://www.gnu.org/licenses/ >
 * @author  Lanteas™ < contact@lanteas.com >
 * @package OpenSub™
*/

$dictionary['OPS_appairage'] = array(
    'table' => 'ops_appairage',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array (
        'name' => 
        array (
          'name' => 'name',
          'vname' => 'LBL_NAME',
          'type' => 'name',
          'link' => true,
          'dbType' => 'varchar',
          'len' => '255',
          'unified_search' => false,
          'full_text_search' => 
          array (
            'boost' => 3,
          ),
          'required' => true,
          'importable' => 'required',
          'duplicate_merge' => 'disabled',
          'merge_filter' => 'disabled',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'size' => '20',
        ),
        'logiciel' => 
          array (
            'required' => false,
            'name' => 'logiciel',
            'vname' => 'LBL_LOGICIEL',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'ops_logiciel_list',
            'studio' => 'visible',
            'dependency' => false,
          ),
        'parent_name' => 
        array (
          'required' => false,
          'source' => 'non-db',
          'name' => 'parent_name',
          'vname' => 'LBL_PARENT_NAME',
          'type' => 'parent',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 25,
          'size' => '20',
          'options' => 'ops_appairage_type_list',
          'type_name' => 'parent_type',
          'id_name' => 'parent_id',
          'parent_type' => 'ops_appairage_type_list',
        ),
        'parent_type' => 
        array (
          'required' => false,
          'name' => 'parent_type',
          'vname' => 'LBL_PARENT_TYPE',
          'type' => 'parent_type',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 255,
          'size' => '20',
          'dbType' => 'varchar',
          'options' => 'ops_appairage_type_list',          
        ),
        'parent_id' => 
        array (
          'required' => false,
          'name' => 'parent_id',
          'vname' => 'LBL_PARENT_ID',
          'type' => 'id',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 36,
          'size' => '20',
        ), 
        'statut' => array(
          'required' => false,
          'name' => 'statut',
          'vname' => 'LBL_STATUT',
          'type' => 'enum',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'inline_edit' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 100,
          'size' => '20',
          'options' => 'ops_statut_appairage_list',
          'studio' => 'visible',
          'dependency' => false
      ),       
    ),
'indices' => array (
        'id'=>array('name' =>'ops_appairagepk', 'type' =>'primary', 'fields'=>array('id')),
        array('name' =>'idx_ops_appairage_id_del', 'type' =>'index', 'fields'=>array('id', 'deleted')),
        array('name' =>'idx_ops_appairage_name_del', 'type' => 'index', 'fields'=>array('name', 'deleted')),
    ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('OPS_appairage', 'OPS_appairage', array('basic'));