<?php
/**
 * @license GNU General Public License < https://www.gnu.org/licenses/ >
 * @author  Lanteas™ < contact@lanteas.com >
 * @package OpenSub™
*/

$dictionary['OPS_type_personne'] = array(
    'table' => 'ops_type_personne',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (

  'categorie_pes' => 
  array (
    'name' => 'categorie_pes',
    'vname' => 'LBL_CATEGORIE_PES',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),

  'nature_juridique_pes' => 
  array (
    'required' => false,
    'name' => 'nature_juridique_pes',
    'vname' => 'LBL_NATURE_JURIDIQUE_PES',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),

  'type_tiers' => 
  array (
    'required' => false,
    'name' => 'type_tiers',
    'vname' => 'LBL_TYPE_TIERS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'T',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_type_tiers',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'imposable' => 
  array (
    'required' => false,
    'name' => 'imposable',
    'vname' => 'LBL_IMPOSABLE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'N',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_tiers_imposable',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'gestion_interets_moratoires' => 
  array (
    'required' => false,
    'name' => 'gestion_interets_moratoires',
    'vname' => 'LBL_GESTION_INTERETS_MORATOIRES',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'O',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_gestion_interets_moratoires',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'gestion_multi_collectivite' => 
  array (
    'required' => false,
    'name' => 'gestion_multi_collectivite',
    'vname' => 'LBL_GESTION_MULTI_COLLECTIVITE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'N',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_gestion_multi_collectivite',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'classe_mouvement' => 
  array (
    'required' => false,
    'name' => 'classe_mouvement',
    'vname' => 'LBL_CLASSE_MOUVEMENT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'P',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_classe_mouvement',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'device' => 
  array (
    'required' => false,
    'name' => 'device',
    'vname' => 'LBL_DEVICE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'E',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_tiers_device',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'code_pays' => 
  array (
    'required' => false,
    'name' => 'code_pays',
    'vname' => 'LBL_CODE_PAYS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '250',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_code_pays',
    'studio' => 'visible',
    'dependency' => false,
  ),

  'code_reglement' => 
  array (
    'required' => false,
    'name' => 'code_reglement',
    'vname' => 'LBL_CODE_REGLEMENT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '22',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ops_tp_code_reglement',
    'studio' => 'visible',
    'dependency' => false,
  ),


),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('OPS_type_personne', 'OPS_type_personne', array('basic','assignable','security_groups'));