<?php 

/**
 * @license GNU General Public License < https://www.gnu.org/licenses/ >
 * @author  Lanteas™ < contact@lanteas.com >
 * @package OpenSub™
*/

$dictionary["User"]["fields"]["employee_unite_travail"] = array (
    'required' => false,
    'name' => 'employee_unite_travail',
    'vname' => 'LBL_EMPLOYEE_UNITE_TRAVAIL',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);
$dictionary["User"]["fields"]["employee_service"] = array (
    'required' => false,
    'name' => 'employee_service',
    'vname' => 'LBL_EMPLOYEE_SERVICE',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);
$dictionary["User"]["fields"]["employee_direction"] = array (
    'required' => false,
    'name' => 'employee_direction',
    'vname' => 'LBL_EMPLOYEE_DIRECTION',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);
$dictionary["User"]["fields"]["employee_pole"] = array (
    'required' => false,
    'name' => 'employee_pole',
    'vname' => 'LBL_EMPLOYEE_POLE',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);
$dictionary["User"]["fields"]["employee_direction_generale"] = array (
    'required' => false,
    'name' => 'employee_direction_generale',
    'vname' => 'LBL_EMPLOYEE_DIRECTION_GENERALE',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);   
$dictionary["User"]["fields"]["boite_aux_lettres"] = array (
    'required' => false,
    'name' => 'boite_aux_lettres',
    'vname' => 'LBL_BOITE_AUX_LETTRES',
    'type' => 'varchar',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);        
?>